package match

import (
	"fmt"
	"strings"
	"time"

	backendai "holdem/backend/internal/ai"
	"holdem/backend/internal/config"
)

// reducer.go is the pure, IO-free façade over the match engine. It exposes the
// exact same state transitions the Service drives, but operating on a
// serializable ActiveMatchRecord instead of the Service's in-memory maps /
// mutex / SQLite store / SSE channels / *ai.Client. This is what the
// WebAssembly referee core (backend/cmd/wasmcore) calls so the Cloudflare
// Workers backend reuses identical rules / eval / replay / prompt logic.
//
// The split mirrors the Service exactly: every Service method here is a thin
// "lock → call pure engine func → persist" wrapper, so the reducer just keeps
// the pure-engine-func part. The Worker/Durable Object side owns the loop
// (runUntilPause), the LLM fetch + retry, persistence, SSE fan-out and alarms.

// CorePending is the JSON-friendly form of pendingEvent for crossing the
// wasm/TS boundary. Field order and names match what publishPending emits.
type CorePending struct {
	Type       string `json:"type"`
	Visibility string `json:"visibility"`
	Payload    any    `json:"payload"`
}

func exportPending(events []pendingEvent) []CorePending {
	out := make([]CorePending, 0, len(events))
	for _, e := range events {
		out = append(out, CorePending{Type: e.EventType, Visibility: e.Visibility, Payload: e.Payload})
	}
	return out
}

// CorePublish mirrors Service.publishPending: it assigns monotonic sequence
// numbers (continuing from seq) to the pending events, appends them to the
// in-flight replay hand (so replay fidelity matches the native backend),
// stamps snapshot.LastEvent/UpdatedAt, and returns the updated record, the
// PUBLIC events the driver should broadcast over SSE, and the new sequence
// counter. Keeping this in Go means the TS driver never reaches into the
// opaque record to manage the event log.
func CorePublish(rec ActiveMatchRecord, pending []CorePending, seq int) (ActiveMatchRecord, []StreamEvent, int) {
	snapshot, hidden := rec.toState()
	broadcast := make([]StreamEvent, 0, len(pending))
	for _, item := range pending {
		seq++
		now := time.Now().UTC()
		event := StreamEvent{
			Type:       item.Type,
			Sequence:   seq,
			Timestamp:  now,
			Visibility: item.Visibility,
			Payload:    item.Payload,
		}
		if hidden != nil && hidden.current != nil {
			hidden.current.Events = append(hidden.current.Events, ReplayEvent{
				Sequence:   seq,
				Type:       item.Type,
				Visibility: item.Visibility,
				Timestamp:  now,
				Payload:    item.Payload,
			})
		}
		snapshot.UpdatedAt = now
		if item.Visibility == "public" {
			eventCopy := event
			snapshot.LastEvent = &eventCopy
			broadcast = append(broadcast, event)
		}
	}
	return recordFrom(snapshot, hidden), broadcast, seq
}

// NextStep tells the driver loop what to do next, replacing the per-iteration
// head of Service.runUntilPause. Kind is one of:
//   - "advance"        : call CoreAdvance (deal next street / settle / next hand)
//   - "ai"             : fetch an LLM decision for Seat (PresetID), then CoreApplyAIDecision
//   - "awaiting_human" : stop; it is the human's turn
//   - "paused"         : stop; paused / manual-without-step / semi-auto hand boundary
//   - "finished"       : stop; match over
//   - "stopped"        : stop; match manually terminated
type NextStep struct {
	Kind     string `json:"kind"`
	Seat     int    `json:"seat"`
	PresetID string `json:"presetId,omitempty"`
}

func (rec ActiveMatchRecord) toState() (Snapshot, *hiddenState) {
	hidden := &hiddenState{
		hand:          rec.Hand,
		replay:        rec.Replay,
		current:       rec.Current,
		decisionTrail: rec.DecisionTrail,
	}
	return rec.Snapshot, hidden
}

func recordFrom(snapshot Snapshot, hidden *hiddenState) ActiveMatchRecord {
	rec := ActiveMatchRecord{Snapshot: snapshot}
	if hidden != nil {
		rec.Hand = hidden.hand
		rec.Replay = hidden.replay
		rec.Current = hidden.current
		rec.DecisionTrail = hidden.decisionTrail
	}
	return rec
}

// CoreCreateMatch mirrors Service.CreateMatch minus the persistence / autoplay
// kickoff: it validates, builds players, deals hand 1 and returns the initial
// record plus the match_created event. Any "@inline:N" markers in
// req.AIPresetIDs must already be resolved by the caller into real ids present
// in presets. The driver (TS) then runs the loop based on the control flags.
//
// id is the match id to use. On the CF backend it is the Durable Object name
// (generated by the Worker) so the match id and DO routing key stay identical;
// pass "" to auto-generate (matching the native newID() path).
func CoreCreateMatch(req CreateRequest, presets []config.Preset, id string) (ActiveMatchRecord, []CorePending, error) {
	if err := validateCreateRequest(req); err != nil {
		return ActiveMatchRecord{}, nil, err
	}
	players, err := buildPlayersFrom(req, presets)
	if err != nil {
		return ActiveMatchRecord{}, nil, err
	}
	players, hand, table, replayHand, err := prepareHand(players, 1, initialDealerSeat(len(players)), req.SmallBlind, req.BigBlind)
	if err != nil {
		return ActiveMatchRecord{}, nil, fmt.Errorf("prepare hand: %w", err)
	}
	if id == "" {
		generated, err := newID()
		if err != nil {
			return ActiveMatchRecord{}, nil, fmt.Errorf("generate match id: %w", err)
		}
		id = generated
	}

	now := time.Now().UTC()
	snapshot := Snapshot{
		ID:           id,
		Status:       statusForTurn(players, hand.CurrentTurnSeat),
		InitialChips: req.InitialChips,
		SmallBlind:   req.SmallBlind,
		BigBlind:     req.BigBlind,
		Players:      players,
		Table:        table,
		Control: ControlState{
			SpectatorMode: req.SpectatorMode,
			SemiAutoMode:  req.SemiAutoMode,
			ManualMode:    req.ManualMode,
			Running:       req.SpectatorMode && !req.ManualMode,
		},
		CreatedAt: now,
		UpdatedAt: now,
	}
	hidden := &hiddenState{
		hand: hand,
		replay: ReplayDetail{
			Summary: ReplaySummary{
				ID:           id,
				Status:       "running",
				CreatedAt:    now,
				PlayerCount:  len(players),
				InitialChips: req.InitialChips,
				SmallBlind:   req.SmallBlind,
				BigBlind:     req.BigBlind,
			},
			Players:   append([]Player(nil), players...),
			CreatedAt: now,
		},
		current: replayHand,
	}
	pending := exportPending([]pendingEvent{publicEvent("match_created", map[string]any{"match": snapshot})})
	return recordFrom(snapshot, hidden), pending, nil
}

// buildPlayersFrom is the pure variant of Service.buildPlayers, taking presets
// as a slice instead of reading s.presets.
func buildPlayersFrom(req CreateRequest, presets []config.Preset) ([]Player, error) {
	presetMap := make(map[string]config.Preset, len(presets))
	for _, preset := range presets {
		presetMap[preset.ID] = preset
	}

	players := []Player{}
	seatOffset := 0
	if !req.SpectatorMode {
		humanName := req.HumanName
		if strings.TrimSpace(humanName) == "" {
			humanName = "你"
		}
		players = append(players, Player{Seat: 0, Name: strings.TrimSpace(humanName), Chips: req.InitialChips, IsHuman: true})
		seatOffset = 1
	}

	totals := map[string]int{}
	for _, presetID := range req.AIPresetIDs {
		if _, ok := presetMap[presetID]; !ok {
			return nil, fmt.Errorf("unknown preset id %q", presetID)
		}
		totals[presetID]++
	}

	ordinals := map[string]int{}
	for index, presetID := range req.AIPresetIDs {
		preset := presetMap[presetID]
		ordinals[presetID]++
		name := strings.TrimSpace(aiDisplayName(req.AIPlayerNames, index))
		if name == "" {
			name = defaultAIPlayerName(preset.Name, ordinals[presetID], totals[presetID])
		}
		players = append(players, Player{Seat: index + seatOffset, Name: name, Chips: req.InitialChips, PresetID: preset.ID})
	}
	return players, nil
}

// CoreDecideNextStep replicates the per-iteration head of runUntilPause: it
// decides whether to advance deterministic state, ask an AI seat, or stop
// (awaiting human / paused / finished / stopped). When it consumes a manual /
// semi-auto step it returns a record with Control.CanStep cleared (mirroring
// clearStepPermission), so the driver should persist the returned record.
func CoreDecideNextStep(rec ActiveMatchRecord) (ActiveMatchRecord, NextStep) {
	snapshot, hidden := rec.toState()

	consumeStep := false
	if hidden != nil && hidden.hand != nil && snapshot.Status != "finished" {
		if snapshot.Control.Stopped || snapshot.Status == "stopped" {
			return rec, NextStep{Kind: "stopped"}
		}
		if shouldPauseAfterHand(snapshot) {
			if !snapshot.Control.CanStep {
				return rec, NextStep{Kind: "paused"}
			}
			consumeStep = true
		}
		seat := hidden.hand.CurrentTurnSeat
		if seat >= 0 && seat < len(snapshot.Players) && !snapshot.Players[seat].IsHuman {
			if snapshot.Control.Paused {
				return rec, NextStep{Kind: "paused"}
			}
			if snapshot.Control.ManualMode {
				if !snapshot.Control.CanStep {
					return rec, NextStep{Kind: "paused"}
				}
				consumeStep = true
			}
		}
	}

	if consumeStep {
		snapshot.Control.CanStep = false
	}
	rec = recordFrom(snapshot, hidden)

	if snapshot.Status == "finished" {
		return rec, NextStep{Kind: "finished"}
	}
	if snapshot.Status == "awaiting_human" {
		return rec, NextStep{Kind: "awaiting_human"}
	}
	if hidden == nil || hidden.hand == nil {
		return rec, NextStep{Kind: "finished"}
	}

	heroSeat := humanSeat(snapshot.Players)
	seat := hidden.hand.CurrentTurnSeat
	if seat >= 0 && seat < len(snapshot.Players) && seat != heroSeat {
		return rec, NextStep{Kind: "ai", Seat: seat, PresetID: snapshot.Players[seat].PresetID}
	}
	return rec, NextStep{Kind: "advance"}
}

// CoreAdvance wraps advanceState (deal next street / settle / start next hand).
func CoreAdvance(rec ActiveMatchRecord) (ActiveMatchRecord, []CorePending, error) {
	snapshot, hidden := rec.toState()
	pending, err := advanceState(&snapshot, hidden)
	if err != nil {
		return ActiveMatchRecord{}, nil, err
	}
	return recordFrom(snapshot, hidden), exportPending(pending), nil
}

// CoreApplyHuman mirrors Service.applyHumanAction minus persistence.
func CoreApplyHuman(rec ActiveMatchRecord, action string, amount int) (ActiveMatchRecord, []CorePending, error) {
	snapshot, hidden := rec.toState()
	if hidden == nil || hidden.hand == nil {
		return ActiveMatchRecord{}, nil, fmt.Errorf("match hand not ready")
	}
	heroSeat := humanSeat(snapshot.Players)
	if heroSeat < 0 {
		return ActiveMatchRecord{}, nil, fmt.Errorf("this match has no human player")
	}
	if hidden.hand.CurrentTurnSeat != heroSeat {
		return ActiveMatchRecord{}, nil, fmt.Errorf("it is not the hero turn")
	}
	pending, err := applyActionToState(&snapshot, hidden, heroSeat, action, amount, "", "")
	if err != nil {
		return ActiveMatchRecord{}, nil, err
	}
	return recordFrom(snapshot, hidden), exportPending(pending), nil
}

// CoreApplyAIDecision mirrors Service.applyAIDecision minus persistence. The
// preset supplies Model/Endpoint for the AILog + DecisionEntry; tokens are not
// needed here. The seat acted on is hidden.hand.CurrentTurnSeat, exactly as in
// the Service path.
func CoreApplyAIDecision(rec ActiveMatchRecord, preset config.Preset, decision backendai.Decision, logEntry backendai.RawLog) (ActiveMatchRecord, []CorePending, error) {
	snapshot, hidden := rec.toState()
	if hidden == nil || hidden.hand == nil {
		return ActiveMatchRecord{}, nil, fmt.Errorf("match hand not ready")
	}
	seat := hidden.hand.CurrentTurnSeat
	if seat < 0 || seat >= len(snapshot.Players) {
		return ActiveMatchRecord{}, nil, fmt.Errorf("ai turn is unavailable")
	}
	if snapshot.Players[seat].IsHuman {
		return ActiveMatchRecord{}, nil, fmt.Errorf("current turn belongs to human")
	}

	hidden.replay.AILogs = append(hidden.replay.AILogs, AILog{
		MatchID:        snapshot.ID,
		HandNumber:     hidden.hand.Number,
		Seat:           seat,
		PlayerName:     snapshot.Players[seat].Name,
		Model:          preset.Model,
		Endpoint:       preset.Endpoint,
		RequestPayload: logEntry.RequestPayload,
		ResponseBody:   logEntry.ResponseBody,
		Structured:     decision,
		CreatedAt:      time.Now().UTC(),
		AttemptCount:   max(1, len(logEntry.Attempts)),
		Error:          logEntry.Error,
	})

	pending := []pendingEvent{replayOnlyEvent("ai_decision_recorded", map[string]any{
		"seat":            seat,
		"playerName":      snapshot.Players[seat].Name,
		"action":          decision.Action,
		"amount":          decision.Amount,
		"publicReason":    decision.PublicReason,
		"privateReason":   decision.PrivateReason,
		"rawResponseBody": logEntry.ResponseBody,
	})}

	appliedDecision := decision
	more, err := applyActionToState(&snapshot, hidden, seat, decision.Action, decision.Amount, decision.PublicReason, decision.PrivateReason)
	if err != nil {
		fallback := fallbackDecision(snapshot, hidden.hand, seat)
		appliedDecision = fallback
		more, err = applyActionToState(&snapshot, hidden, seat, fallback.Action, fallback.Amount, fallback.PublicReason, fallback.PrivateReason)
		if err != nil {
			return ActiveMatchRecord{}, nil, err
		}
	}
	entry := DecisionEntry{
		Seat:          seat,
		PlayerName:    snapshot.Players[seat].Name,
		Stage:         hidden.hand.Stage,
		Action:        appliedDecision.Action,
		Amount:        appliedDecision.Amount,
		PublicReason:  appliedDecision.PublicReason,
		PrivateReason: privateReasonForView(snapshot.Players, appliedDecision.PrivateReason),
		Model:         preset.Model,
		Endpoint:      preset.Endpoint,
	}
	hidden.hand.DecisionLog = append(hidden.hand.DecisionLog, entry)
	hidden.decisionTrail = append(hidden.decisionTrail, entry)
	rebuildSnapshotTable(&snapshot, hidden)
	pending = append(pending, more...)
	return recordFrom(snapshot, hidden), exportPending(pending), nil
}

// CoreBuildAIRequestBody builds the byte-exact LLM request body for an AI seat
// (the Worker performs the fetch). Mirrors what runUntilPause +
// ai.Client.Decide would send for the given attempt.
func CoreBuildAIRequestBody(rec ActiveMatchRecord, seat int, attempt int, lastHint string, preset config.Preset) ([]byte, error) {
	snapshot, hidden := rec.toState()
	if seat < 0 || seat >= len(snapshot.Players) {
		return nil, fmt.Errorf("seat out of range")
	}
	input := buildPromptInput(snapshot, hidden, seat)
	return backendai.BuildRequestBody(preset, input, attempt, lastHint)
}

// CoreApplyControl mirrors Service.ControlMatch's state machine minus the
// autoplay kickoff + SQLite persistence. For "stop" it also finalizes the
// replay (mirroring persistStoppedReplayLocked).
func CoreApplyControl(rec ActiveMatchRecord, action string) (ActiveMatchRecord, error) {
	snapshot, hidden := rec.toState()
	switch action {
	case "pause":
		snapshot.Control.Paused = true
	case "resume":
		snapshot.Control.Paused = false
		snapshot.Control.CanStep = snapshot.Status == "hand_complete"
		snapshot.Control.ManualMode = false
	case "auto_on":
		snapshot.Control.SemiAutoMode = false
		snapshot.Control.ManualMode = false
		snapshot.Control.Paused = false
		snapshot.Control.CanStep = false
	case "semi_auto_on":
		snapshot.Control.SemiAutoMode = true
		snapshot.Control.ManualMode = false
		snapshot.Control.Paused = false
		snapshot.Control.CanStep = false
	case "manual_on":
		snapshot.Control.ManualMode = true
		snapshot.Control.SemiAutoMode = false
		snapshot.Control.Paused = false
		snapshot.Control.CanStep = false
	case "manual_off":
		snapshot.Control.ManualMode = false
		snapshot.Control.SemiAutoMode = false
		snapshot.Control.CanStep = false
		snapshot.Control.Paused = false
	case "step":
		snapshot.Control.ManualMode = true
		snapshot.Control.SemiAutoMode = false
		snapshot.Control.Paused = false
		snapshot.Control.CanStep = true
	case "stop":
		snapshot.Control.Stopped = true
		snapshot.Status = "stopped"
		finalizeStoppedReplay(&snapshot, hidden)
		if snapshot.Warning != "" {
			snapshot.Warning = "比赛已手动终止；" + snapshot.Warning
		} else {
			snapshot.Warning = "比赛已手动终止"
		}
	case "continue":
		snapshot.Control.Paused = false
		snapshot.Control.CanStep = snapshot.Status == "hand_complete"
	default:
		return ActiveMatchRecord{}, fmt.Errorf("unsupported control action %q", action)
	}
	return recordFrom(snapshot, hidden), nil
}

// finalizeStoppedReplay mirrors Service.persistStoppedReplayLocked minus the
// store write: it appends the in-flight hand and stamps the replay summary.
func finalizeStoppedReplay(snapshot *Snapshot, hidden *hiddenState) {
	if hidden == nil {
		return
	}
	appendCurrentReplayHandIfNeeded(snapshot, hidden)
	hidden.replay.Summary.Status = "stopped"
	hidden.replay.Summary.WinnerName = snapshot.WinnerName
	hidden.replay.Summary.HandsPlayed = len(hidden.replay.Hands)
	hidden.replay.Summary.FinishedAt = time.Now().UTC()
}

// CoreRecordSummary / CoreReplayDetail expose the projections the Worker needs
// for /api/records and /api/replays without re-deriving them in TS.
func CoreRecordSummaryFromSnapshot(snapshot Snapshot) RecordSummary {
	return recordSummaryFromSnapshot(snapshot)
}

func CoreRecordSummaryFromReplay(replay ReplayDetail) RecordSummary {
	return recordSummaryFromReplay(replay)
}

func CoreNormalizeReplay(replay ReplayDetail) ReplayDetail {
	return normalizeReplayDetail(replay)
}
