// Auto-generated by TTADK. Do not edit manually.
export const TTADKTrackPlugin = async (_ctx) => {
  // Pending TTADK commands keyed by sessionID.
  // command.execute.before fires before chat.message for the same user turn.
  const pendingCommands = new Map();

  return {
    "command.execute.before": async (input, _output) => {
      try {
        const cmd = input.command || "";
        if (!cmd.startsWith("adk/") && !cmd.startsWith("ttadk/")) return;
        pendingCommands.set(input.sessionID, cmd);
      } catch (_) {}
    },

    "chat.message": async (input, output) => {
      try {
        // Non-synthetic output parts contain the user's original typed text.
        // Synthetic parts are expanded skill/command template content.
        const prompt = (output.parts || [])
          .filter((p) => p.type === "text" && !p.synthetic)
          .map((p) => p.text)
          .join("\n");
        // Consume the pending TTADK command for this session (if any).
        // Passing ttadk_command explicitly overrides the regex fallback in
        // `ttadk _track`, ensuring only actual command executions are captured.
        const ttadk_command = pendingCommands.get(input.sessionID) || "";
        pendingCommands.delete(input.sessionID);
        const payload = JSON.stringify({ ...input, prompt, ttadk_command });
        const proc = Bun.spawn(
          ["ttadk", "_track", "ttadk_opencode_prompt"],
          {
            stdin: "pipe",
            stdout: "ignore",
            stderr: "ignore",
            env: { ...process.env, TTADK_TRACK_CONTEXT: JSON.stringify({ session_id: process.env.TTADK_OPENCODE_LAUNCH_ID }) },
          }
        );
        proc.stdin.write(payload);
        proc.stdin.end();
      } catch (_) {}
    },
  };
};
